"""Regras preditivas simples para antecipacao de alarmes e risco de trip."""

from __future__ import annotations


PREDICTIVE_RULES: dict[str, dict[str, object]] = {
    "pv_vib_estagio_1_mils": {
        "subsystem": "vibracao",
        "label": "Vibracao 1o estagio",
        "direction": "up",
        "threshold": 1.3,
        "criticality": "critica",
        "lookback_points": 24,
        "forecast_horizon_minutes": 240,
        "trip_horizon_minutes": 45,
        "min_slope_per_hour": 0.06,
        "min_current_ratio": 0.55,
        "trip_related": True,
        "prescriptive_signal": "pv_vib_estagio_1_mils",
    },
    "pv_vib_estagio_2_mils": {
        "subsystem": "vibracao",
        "label": "Vibracao 2o estagio",
        "direction": "up",
        "threshold": 1.3,
        "criticality": "critica",
        "lookback_points": 24,
        "forecast_horizon_minutes": 240,
        "trip_horizon_minutes": 45,
        "min_slope_per_hour": 0.06,
        "min_current_ratio": 0.55,
        "trip_related": True,
        "prescriptive_signal": "pv_vib_estagio_2_mils",
    },
    "pv_vib_estagio_3_mils": {
        "subsystem": "vibracao",
        "label": "Vibracao 3o estagio",
        "direction": "up",
        "threshold": 1.3,
        "criticality": "critica",
        "lookback_points": 24,
        "forecast_horizon_minutes": 240,
        "trip_horizon_minutes": 45,
        "min_slope_per_hour": 0.06,
        "min_current_ratio": 0.55,
        "trip_related": True,
        "prescriptive_signal": "pv_vib_estagio_3_mils",
    },
    "pv_temp_oleo_lubrificacao_c": {
        "subsystem": "lubrificacao",
        "label": "Temperatura do oleo",
        "direction": "up",
        "threshold": 57.0,
        "criticality": "alta",
        "lookback_points": 24,
        "forecast_horizon_minutes": 240,
        "trip_horizon_minutes": 60,
        "min_slope_per_hour": 1.2,
        "min_current_ratio": 0.82,
        "trip_related": False,
        "prescriptive_signal": "pv_temp_oleo_lubrificacao_c",
    },
    "pv_corr_motor_a": {
        "subsystem": "motor",
        "label": "Corrente do motor",
        "direction": "up",
        "threshold": 185.0,
        "criticality": "alta",
        "lookback_points": 24,
        "forecast_horizon_minutes": 180,
        "trip_horizon_minutes": 45,
        "min_slope_per_hour": 6.0,
        "min_current_ratio": 0.8,
        "trip_related": True,
        "prescriptive_signal": "pv_corr_motor_a",
    },
    "pv_temp_fase_a_do_estator_c": {
        "subsystem": "motor",
        "label": "Temperatura do estator fase A",
        "direction": "up",
        "threshold": 166.0,
        "criticality": "alta",
        "lookback_points": 24,
        "forecast_horizon_minutes": 300,
        "trip_horizon_minutes": 60,
        "min_slope_per_hour": 2.0,
        "min_current_ratio": 0.75,
        "trip_related": True,
        "prescriptive_signal": "pv_temp_fase_a_do_estator_c",
    },
    "pv_temp_fase_b_do_estator_c": {
        "subsystem": "motor",
        "label": "Temperatura do estator fase B",
        "direction": "up",
        "threshold": 166.0,
        "criticality": "alta",
        "lookback_points": 24,
        "forecast_horizon_minutes": 300,
        "trip_horizon_minutes": 60,
        "min_slope_per_hour": 2.0,
        "min_current_ratio": 0.75,
        "trip_related": True,
        "prescriptive_signal": "pv_temp_fase_b_do_estator_c",
    },
    "pv_temp_fase_c_do_estator_c": {
        "subsystem": "motor",
        "label": "Temperatura do estator fase C",
        "direction": "up",
        "threshold": 166.0,
        "criticality": "alta",
        "lookback_points": 24,
        "forecast_horizon_minutes": 300,
        "trip_horizon_minutes": 60,
        "min_slope_per_hour": 2.0,
        "min_current_ratio": 0.75,
        "trip_related": True,
        "prescriptive_signal": "pv_temp_fase_c_do_estator_c",
    },
    "pv_temp_rolamento_dianteiro_motor": {
        "subsystem": "motor",
        "label": "Temperatura do rolamento dianteiro",
        "direction": "up",
        "threshold": 85.0,
        "criticality": "critica",
        "lookback_points": 24,
        "forecast_horizon_minutes": 240,
        "trip_horizon_minutes": 45,
        "min_slope_per_hour": 1.5,
        "min_current_ratio": 0.75,
        "trip_related": True,
        "prescriptive_signal": "pv_temp_rolamento_dianteiro_motor",
    },
    "pv_pres_descarga_bar": {
        "subsystem": "ar_processo",
        "label": "Pressao de descarga",
        "direction": "up",
        "threshold": 7.8,
        "criticality": "alta",
        "lookback_points": 24,
        "forecast_horizon_minutes": 180,
        "trip_horizon_minutes": 45,
        "min_slope_per_hour": 0.2,
        "min_current_ratio": 0.85,
        "trip_related": False,
        "prescriptive_signal": "pv_pres_descarga_bar",
    },
    "pv_pres_sistema_bar": {
        "subsystem": "ar_processo",
        "label": "Pressao do sistema",
        "direction": "up",
        "threshold": 6.9,
        "criticality": "alta",
        "lookback_points": 24,
        "forecast_horizon_minutes": 180,
        "trip_horizon_minutes": 45,
        "min_slope_per_hour": 0.15,
        "min_current_ratio": 0.85,
        "trip_related": False,
        "prescriptive_signal": "pv_pres_sistema_bar",
    },
}
